version: 0.2

phases:
    install:
        commands:
            - npm install -g typescript
    build:
        commands:
            - npm run build
artifacts:
    files:
        - "**/*"
    base-directory: "build"
